[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "baator-v0.4-model"
version = "0.4.0"
description = "Reconstructed model scaffold for Baator v0.4"
authors = [{name="Valkyr"}]
