from __future__ import annotations
from typing import Protocol, Iterable, Optional, Tuple, Dict, Any

class Repository(Protocol):
    def list_worlds(self) -> Iterable[str]: ...
    def load_world(self, name: str) -> Optional[Dict[str, Any]]: ...
    def save_world(self, name: str, data: Dict[str, Any]) -> None: ...
    def load_pack(self, pack_name: str) -> Dict[str, Any]: ...